<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Consumer</h4>
        </div>
    </div>
</div>

<!-- end page title -->
<div class="paper container">

    <div class="row" id="form">
        <div class="col-6 col">
            <div class="form-group">
                <label for="broker">Broker IP / Address</label>
                <input type="text" placeholder="eg. 192.168.10.10" id="broker" name="broker" class="form-control">
            </div>
        </div>
        <div class="col-6 col">
            <div class="form-group">
                <label for="topic">Topic Name</label>
                <input type="text" placeholder="eg. newTopic" id="topic" name="topic" class="form-control">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 col">
            <button id="start" class="btn btn-success">Start</button>
            <button id="stop" class="btn btn-danger">Stop</button>
        </div>
    </div>

</div>
<br>
<div class="paper container">
    <pre id="console" class="console_consume"></pre>
</div>

<script src="/js/consumer.js"></script>

