<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/css/paper.min.css">
    <script src="/js/jquery-3.3.1.min.js"></script>
    <title>Kafka Author - Consume</title>
</head>
<body>
<div class="paper container">
    <div class="row">
        <div class="col-12 col">
            <img src="/img/logo.webp" class="no-border float-left logo">
            <h3> Kafka Consumer</h3>
            <p>Consume a topic from a broker</p>
        </div>
    </div>
    <div class="row" id="form">
        <div class="col-6 col">
            <div class="form-group">
                <label for="broker">Broker IP / Address</label>
                <input type="text" placeholder="eg. 192.168.10.10" id="broker" name="broker">
            </div>
        </div>
        <div class="col-6 col">
            <div class="form-group">
                <label for="topic">Topic Name</label>
                <input type="text" placeholder="eg. newTopic" id="topic" name="topic">
            </div>
            <button id="start" class="btn-success">Start</button>
            <button id="stop" class="btn-danger">Stop</button>
        </div>
    </div>
</div>
<br>
<div class="paper container">
    <pre id="console"></pre>
</div>

</body>
<style>
    .logo{
        height:200px;
    }
    #console{
        width: auto;
        background-color: #41403e;
        color: limegreen;
    }
    #stop{
        display: none;
    }
</style>
<script>
    $(document).ready(function() {
        var tid;


        $(window).on("unload", function(e) {
            saveSettings();
        });
        loadSettings();
        $('#start').click(function(){
            $('#start').hide();
            $('#stop').show();
            tid = setInterval(consume, 3000);
        })
        $('#stop').click(function(){
            $('#start').show();
            $('#stop').hide();
            clearInterval(tid);
        })
    });

    function consume()
    {
        $.post( "/consume", $( "#form :input" ).serialize() )
            .done(function( data ) {
                var d = new Date();
                if(data){
                    $('#console').prepend(d + " <br>" + data + "<br><br>");
                }
            });
    }

    function loadSettings()
    {
        $('#topic').val(localStorage.topic);
        $('#broker').val(localStorage.broker);
    }

    function saveSettings()
    {
        localStorage.broker = $('#broker').val();
        localStorage.topic = $('#topic').val();
    }
</script>
</html>

