<div class="row">
    <div class="col-6">
        <div class="card-box">
            <h4 class="header-title">Send Event</h4>
            <p class="sub-header">
                Set up an event payload and publish to a kafka topic
            </p>

            <div class="row">
                <div class="col-12">
                    <div class="p-2">
                        <div class="form-horizontal" role="form" id="form">
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label" for="broker">Broker IP / Domain</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" placeholder="eg. 192.168.10.10" id="broker" name="broker">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label" for="topic">Topic</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" placeholder="eg. newTopic" id="topic" name="topic">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label" for="payload">Event Payload</label>
                                <div class="col-sm-10">
                                    <textarea id="payload" class="form-control" cols="400" rows="5" name="payload" placeholder='eg. {"name":"mike bywater"}'></textarea>
                                </div>
                            </div>
                            <button id="submit" class="btn-success">Submit</button>
                        </div>
                    </div>
                </div>

            </div>
            <!-- end row -->

        </div> <!-- end card-box -->
    </div><!-- end col -->
    <div class="col-6">
        <div class="card-box">
            <h4 class="header-title">Recent Payloads</h4>
            <p class="sub-header">
                List of recently sent payloads
            <ul id="topics">
            </ul>
        </div>
    </div>
</div>
<!-- end row -->

<div class="row">
    <div class="col-12 col">
            <pre id="console"></pre>
    </div>
</div>

<style>
    #console{
        width: auto;
        background-color: #41403e;
        color: limegreen;
    }
</style>
<script src="/js/producer.js"></script>

